### ISSUE TITLE
FtpClient::put() does not timeouts in some circumstances

### ISSUE THREAD

**Issue by pvanek** [qorelanguage/qore#3036] opened 2018-10-12 11:46 UTC
I think it can be caused by a restrictive firewall. Because the PORT mode requires some port usage...

```
%new-style

FtpClient ftp("ftp://...");
ftp.connect();
ftp.setModePORT(); # it freezes - sometimes some attempts goes through, rest is frozen
#ftp.setModeAuto(); # this one works fine all the time

for (int i = 0; i < 100; i++) {
    auto ret = ftp.put("DHL-DEL_0031963334_PDF.SAP-DEL", "test.pdf");
    printf("%n: %d: %N\n", now(), i, ret);
}
```

**Comment by davidnich** [comment] 2018-10-12 12:09
duplicate of #3031

**Closed as completed by davidnich** 2018-10-12 12:09 UTC
Labels: bug, duplicate, c++
