### ISSUE TITLE
Qore is unable to call callable object members directly; call_function() must be used instead

### ISSUE THREAD

**Issue by pavelkveton** [qorelanguage/qore#1001] opened 2016-06-20 12:23 UTC
(migrated from Qorus issue https://bugs.qoretechnologies.com/issues/1084):

when the method lookup fails, a member lookup should be attempted, but instead a PARSE-EXCEPTION is raised

**Comment by davidnich** [comment] 2016-06-21 09:04
note: works wtih %new-style within the object:

``` Shell
prompt% qore -ne 'class T { public { code x = sub () { printf("hi\n"); }; } constructor() { x(); }} T t();'
hi
```

but not outside the object:

``` Shell
prompt% qore -ne 'class T { public { code x = sub () { printf("hi\n"); }; }} T t(); t.x();'
warning encountered at <command-line>:1
NON-EXISTENT-METHOD-CALL: call to non-existent method 'T::x()'; this call will be evaluated at run-time, so if the method is called on an object of a subclass that implements this method, then it could be a valid call, however in any other case it will result in a run-time exception.  To avoid seeing this warning, use the cast<> operator (note that if the cast is invalid at run-time, a run-time exception will be raised) or turn off the warning by using '%disable-warning non-existent-method-call' in your code
unhandled QORE System exception thrown in TID 1 at 2016-06-21 11:02:51.274672 Tue +02:00 (CEST) at <command-line>:1
METHOD-DOES-NOT-EXIST: no method T::x() has been defined and no pseudo-method <object>::x() is available
```

(note the warning and the runtime error)

**Comment by tethal** [comment] 2016-06-21 09:06
duplicate of #39

**Closed as completed** 2016-06-21 09:07 UTC
Labels: duplicate, feature, c++
