### ISSUE TITLE
ThreadPool::submit with parameters

### ISSUE THREAD

**Issue by tmandys** [qorelanguage/qore#2676] opened 2018-03-04 21:16 UTC
When passing "id" then no copy is passed to submit pool queue and worker may get wrong value so we must pass real constant enough value. Closure feature or bug ?

```
%new-style

ThreadPool tp();

sub worker1(string id) {
    printf("WORKER1: %d\n", id);
}

sub worker2(reference id) {
    printf("WORKER2: %d\n", id);
}

list l;
for (int i=0; i<10; i++) {
    push l, string(i);
}

foreach string id in (l) {
    # BUG: when passing "id" then no copy is passed to submit pool queue and worker may get wrong value
    tp.submit(sub() {call_function(\worker1(), id); } );
}

list l2 = ();
for (int i=0; i<l.size(); i++) {
    # so we must pass real constant enough value
    string e = l[i]+" ";
    push l2, e;
    tp.submit(sub() {call_function(\worker2(), \e); } );
}

WORKER1: 5
WORKER1: 9
WORKER1: 9
WORKER1: 9
WORKER1: 9
WORKER1: 9
WORKER1: 9
WORKER1: 9
WORKER1: 9
WORKER2: 2
WORKER2: 8
WORKER2: 7
WORKER2: 4
WORKER2: 9
WORKER2: 5
WORKER2: 6
WORKER2: 0
WORKER2: 1
WORKER2: 3
WORKER1: 9

```

**Comment by davidnich** [comment] 2018-03-05 04:28
@tmandys this is due to the fact that the `id` local variable in the `foreach` loop is the same variable in each loop, so the same local variable is bound to the closure each time.  If you change it as follows, then it will work as you expect:
```
foreach string id in (l) {
    string id1 = id;
    tp.submit(sub() {call_function(\worker1(), id1); } );
}
```

**Comment by davidnich** [comment] 2018-03-05 17:29
@tmandys I'm going to close this sine it's working as designed; if you have any issues, please reopen it

**Closed as completed by davidnich** 2018-03-05 17:29 UTC
Labels: notabug
