### ISSUE TITLE
returning a hash that is not initialized causes runtime exception

### ISSUE THREAD

**Issue by pavelkveton** [qorelanguage/qore#1240] opened 2016-09-12 07:59 UTC
This I consider highly confusing. I declare a hash (that is initialized to NOTHING), and I return the VERY SAME data type from a function, which produces an exception:

```
kveton@kvela:~$ qore -ne "class X { private { hash h; } hash get() { return h; }}; X x(); x.get();"
unhandled QORE System exception thrown in TID 1 at 2016-09-12 09:54:07.109267 Mon +02:00 (CEST) in X::get() (<command-line>:1, user code)
RUNTIME-TYPE-ERROR: <return statement> expects type 'hash', but got no value instead
call stack:
  1: X::get() (<command-line>:1, user code)
```

**Comment by davidnich** [comment] 2016-09-12 08:23
this is a duplicate of #488 and is planned to be addressed with "hard qore" with the parse option `%strong-types` - also related to #187 

By the way there is code already in place to support this (ensuring basic types always have their default "empty" value), but putting it in place causes massive compatibility issues, therefore it needs to be carefully planned and executed.

**Closed as completed by davidnich** 2016-09-12 08:23 UTC
Labels: bug, duplicate, confusing, types
