### ISSUE TITLE
CsvUtil does not support the standard approach for escaping quotes

### ISSUE THREAD

**Issue by davidnich** [qorelanguage/qore#604] opened 2016-03-13 15:08 UTC
from https://tools.ietf.org/html/rfc4180

`"If double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped by preceding it with another double quote."`

**Comment by pavelkveton** [comment] 2016-03-14 12:19
following Ondra's advice, I'm changing milestone to 0.8.11.1, I'll fix the bug there and then we can consider changing the default escape char in develop branch (0.8.12 milestone), since the issue is already fixed in develop:
https://github.com/qorelanguage/qore/commit/cb1e0ae215e12138dd7cc49ae0f8803afe956480

**Closed as completed** 2016-03-14 14:59 UTC
Labels: bug, fixed
