### ISSUE TITLE
sprintf/vprintf bad output

### ISSUE THREAD

**Issue by petrycta** [qorelanguage/qore#3184] opened 2018-12-15 21:23 UTC
Problem code:
```
string msg = sprintf("% f\n", NOTHING);
printf("%s", msg);
```

expected output: "% f"
current output:    "0.000000"

`sprintf("% f\n");` - works fine

**Comment by davidnich** [comment] 2018-12-15 21:24
@petrycta use `%%` in a string format to get a single `%` in the output - i.e. `string msg = sprintf("%% f\n", NOTHING);`

**Comment by petrycta** [comment] 2018-12-15 21:33
@davidnich cool, thanks, but sometimes messages are send to logger as already formatted and logger tries to format it again ... . e.g 

does not work for this case:
string msg = sprintf("%% f\n", NOTHING);
printf(sprintf("%s", msg), NOTHING);

**Comment by petrycta** [comment] 2018-12-15 21:35
@davidnich I was expecting that NOTHING, means really nothing, so 
sprintf("% f\n", NOTHING);
sprintf("% f\n");
should behave the same

**Comment by davidnich** [comment] 2018-12-16 06:41
@petrycta if a message is already formatted, then it must not be formatted again, or you will get errors like that - I recommend using another function or method to process already-formatted messages if possible - this is not a bug in `sprintf()` in my opinion but rather an issue that should be addressed in your logger implementation.

**Comment by petrycta** [comment] 2018-12-16 09:39
@davidnich if 
sprintf("% f\n", NOTHING);
sprintf("% f\n");
gives different outputs and it is ok, then there is no issue to qore

**Comment by geckon** [comment] 2018-12-17 14:08
Formatting an already formatted string is surely not a bug in `sprintf` but I'm still interested in the other "issue" here.

Why do these two behave differently? And is it alright? It seems confusing at the very least.
```
sprintf("% f\n", NOTHING);
sprintf("% f\n");
```

Thanks!

**Comment by geckon** [comment] 2018-12-17 14:09
```
$ qore -X 'sprintf("% f")'
"% f"

$ qore -X 'sprintf("% f", NOTHING)'
"0.000000"
```

**Closed as completed** 2018-12-23 20:49 UTC
Labels: bug, fixed, c++
