### ISSUE TITLE
AbstractQuantifiedBidirectionalIterator unavailable

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#968] opened 2016-06-14 13:38 UTC
Is AbstractQuantifiedBidirectionalIterator really available ?

```
PARSE-EXCEPTION: reference to undefined class 'AbstractQuantifiedBidirectionalIterator'

PARSE-EXCEPTION: cannot find class 'AbstractQuantifiedBidirectionalIterator' in any namespace 'Qore'
```

**Comment by omusil24** [comment] 2016-06-14 13:43
Example:

```
#!/usr/bin/env qore
# -*- mode: qore; indent-tabs-mode: nil -*-

%new-style
%enable-all-warnings
%require-types
%strict-args
%disable-warning unreferenced-variable

AbstractQuantifiedBidirectionalIterator a = new HashIterator();

-------------

unhandled QORE System exception thrown in TID 1 at 2016-06-14 15:47:21.686030 Tue +02:00 (CEST) at ./lalala.qtest:10
PARSE-EXCEPTION: reference to undefined class 'AbstractQuantifiedBidirectionalIterator'
```

@tethal

**Comment by tethal** [comment] 2016-06-15 11:28
Caused by the fact that this class has no methods -> it was not marked as system -> it was never copied into the Program object

**Closed as completed** 2016-06-15 11:29 UTC
Labels: bug, fixed
