### ISSUE TITLE
module-oracle: NTY (objects and collections) truncate LOB attributes (size/4)

### ISSUE THREAD

**Issue by pvanek** [qorelanguage/qore#1802] opened 2017-04-10 11:11 UTC
test script:

```
%new-style
%requires oracle

Datasource ds("oracle:omquser/omquser@xbox");
on_exit ds.rollback();

hash ret = ds.exec("begin nty_test.test(:o); end;", placeholderOracleObject("test_object"));

printf("%N\n", ret);
```

type:

```
create or replace TYPE         test_object
    authid current_user
as object (
    a_text varchar2(10),
    a_number number/*(3)*/,
    a_textc char(10),
    a_clob clob,
    a_date date
)
```

package:

```
create or replace 
package nty_test as 

  procedure test(o out test_object);
  

end nty_test;
/
```
```
create or replace
package body nty_test as

  procedure test(o out test_object) as
  begin
    o := test_object(
    'some text',
    3,
    'c',
    '{"requestContext":{"shipTo":"99812340"
,"timeZone":"0"
,"langCode":"en"
},"transactionId":"6104"
,"depResellerId":"99812340"
,"orders":[{"orderNumber":"8000226872"
,"orderDate":""
,"orderType":"OR"
,"customerId":"452390"
,"deliveries":[{"deliveryNumber":"25676169"
,"shipDate":"2017-03-20T20:33:24Z"
,"devices":[{"deviceId":"352798754296065"
}]}]}]}',
/*
    '1234567890
1234567890
1234567890
1234567890
1234567890
1234567890
1234567890
1234567890
1234567890
1234567890
1234567890
1234567890
1234567890
1234567890
1234567890',
*/
    sysdate);
  end test;

end nty_test;
/
```

**Comment by pvanek** [comment] 2017-04-10 11:13
issue is located in objToQore and collToQore (file oracleobject.cpp). 

	 case SQLT_CLOB:
	 case SQLT_BLOB: {

**Comment by davidnich** [comment] 2017-04-13 14:36
@pvanek please set the milestone if known when assigning or starting to work on a defect; Martin indicated 0.8.12.10

**Comment by martin-zemek** [comment] 2017-05-12 08:03
In the function OCI_LobRead2() (file ocilib/lob.cpp)
byte_count is set as char_count*4     (UTF8_BYTES_PER_CHAR = 4)
... if we are in the CLOB case (char_count > 0 && byte_count == 0) and pOCILib->nls_utf8 == TRUE.
But this code is not in action - which is the cause of the bug. The above conditions are not met.

To fix the bug we must ensure that:
1. OCI_LobRead2() obtains input param byte_count = 0 (which was not the case so far - needs to be fixed in oracleobject.cpp)
2. pOCILib->nls_utf8 = TRUE

pOCILib->nls_utf8 is set in OCI_Initialize2() in the file ocilib/library.cpp using
the environment variable NSL_LANG (getenv("NLS_LANG");)
If we comment out this code and set pOCILib->nls_utf8 = TRUE unconditionally the bug is fixed.

I've pushed the complete fix to module-oracle branch bugfix/1802_nty_truncates_lobs,
but the question - probably to David - is whether we can have there the unconditional pOCILib->nls_utf8 = TRUE
or whether we want to use the environment variable NLS_LANG somehow.

**Comment by davidnich** [comment] 2017-05-12 08:20
> the question - probably to David - is whether we can have there the unconditional pOCILib->nls_utf8 = TRUE

@martin-zemek this is really more a question to @pvanek who understands the consequences better
@pvanek what do you think?

**Comment by pvanek** [comment] 2017-05-12 08:27
I would say, that we can ignore NLS_LANG and stay with Qore's internal language/charset handling. It seems more logical to me.

I cannot say if "pOCILib->nls_utf8 = TRUE" is correct from Qore perspective, as it can use different native encoding (ok, utf8 is the most common, but...)

**Comment by davidnich** [comment] 2017-05-12 08:30
@pvanek but it's not worse than using `NLS_LANG` at least?

@martin-zemek can you test this with a DB connection using `we8iso88591` for example?

**Comment by martin-zemek** [comment] 2017-05-12 08:32
Of course we can also do the fix by multiplying the input param byte_count by 4 and not do anything else. I've tried this before and it works - having there bigger number than necessary does not do any harm.

**Comment by davidnich** [comment] 2017-05-12 08:51
@martin-zemek please find out what `pOCILib->nls_utf8 = TRUE` means by looking at the ocilib source code (meaning the impact of setting this value) - it's probably safe for us and means that our native character encoding handling will be used and our literal byte length are used in the ocilib calls, whereas without it, it probably means that it assumes character widths are given and with UCS32 or something like that it means 1 char = 4 bytes.

**Comment by martin-zemek** [comment] 2017-06-30 11:05
In the end the fix is different from what was discussed above (we won't set pOCILib->nls_utf8 = true uncoditionally). The fix consist in passing correct arguments to OCI_LobRead2(), namely char_len is set to byte_len multiplied by encoding->getMaxCharWidth().

**Comment by pavelkveton** [comment] 2017-08-02 12:32
ok, giving up. I'd like to understand the following: IF we are passing in and out an ASCII (7bit) string, why (before the fix) the data is also truncated. But I got lost inside the mess of OCILIB, converting and packing the strings...

**Closed as completed** 2017-08-02 12:43 UTC
Labels: bug, module, c++
