### ISSUE TITLE
slightly confusing behaviour of map with no value input

### ISSUE THREAD

**Issue by gamato** [qorelanguage/qore#939] opened 2016-06-01 12:53 UTC
Let's have `*list x`.
Now, when `x` has no value, the following produces 2 different results:
`map $1, x;` returns `NOTHING`
`map $1, x.iterator();` returns `()`

Is this expected ? .. And is it wanted ?

Notes:

```
$ qore -X 'map $1, ()'
<EMPTY LIST>

$ qore -X 'map $1, {}'
<EMPTY HASH>
```

So I guess it's about that `map` has no idea what to return if input is no value.

**Comment by tethal** [comment] 2016-06-01 13:11
I believe that

```
map $1, NOTHING;
```

and 

```
map $1, {};
```

are explained by this in the documentation:

> If the second argument is not a list or an object inheriting AbstractIterator, then map_expression is executed on the single value and the result is returned (assuming that any select_expression accepts the value).

This:

```
map $1, ()
```

is OK, the expression `$1` has been applied to all 0 elements of the input list.

The last case,

```
map $1, NOTHING.iterator()
```

is caused by the fact that `NOTHING.iterator()` returns an empty iterator. According to the documentation, `<nothing>.iterator()` returns `SingleValueIterator`. ~~However, the fact that `SingleValueIterator` is empty for NOTHING is not documented.~~

EDIT: it is [documented](https://qore.org/manual/develop/lang/html/class_qore_1_1_single_value_iterator.html#a2923e45802fc98a2fb9207989710de1d):

> This method returns True and False alternately unless it has no value to iterate, in which case it returns only False.

So I would say that it is expected (since it is documented).

**Comment by gamato** [comment] 2016-06-01 14:08
OK, clear, thanks.

**Comment by tethal** [comment] 2016-06-01 14:28
In that case I'm closing this. Feel free to reopen if you have further questions or if you think that something should be done about this.

**Closed as completed by tethal** 2016-06-01 14:28 UTC
Labels: confusing, notabug
