### ISSUE TITLE
fix Mime module to allow binary files uploading

### ISSUE THREAD

**Issue by petrytar** [qorelanguage/qore#2936] opened 2018-08-08 14:04 UTC
When trying to upload binary files, the exception is thrown `MULTIPART-PARSEBODY-ERROR: cannot find closing boundary %y in body`.

**Comment by davidnich** [comment] 2018-08-08 14:07
@petrytar can you please be more specific about the problem or error you are getting?  some example code reproducing the problem would be ideal - thx

**Comment by davidnich** [comment] 2018-08-08 14:08
@petrytar I'm asking because it's also assigned to me - if you will be making the fix, then it's enough to get the pull request when it's ready with tests + relnotes etc

**Comment by petrytar** [comment] 2018-08-08 14:15
My bad, description updated. Yes I already fixed it. Small fix is on its way.

**Comment by sejvlond** [comment] 2019-04-15 11:55
@petrycta @petrytar can u pls check whether it's done and close it? btw, which account are you using?

**Comment by petrycta** [comment] 2019-04-15 12:13
@sejvlond hi, unfortunately I know nothing about it, my changes was rejected, and as far as I remember @pvanek agreed to take a look on it, after I had warned @davidnich that it might takes me a lot of time to analyze&solve thus bug

**Comment by pvanek** [comment] 2019-04-15 13:13
a test case showing this error is in the `bugfix/2936-mime_binary` branch

**Comment by sejvlond** [comment] 2019-04-16 08:50
thx, I will leave the bug opened then without anyone assigned and we will fix it later

**Closed as completed** 2019-06-17 11:09 UTC
Labels: bug, qore
