### ISSUE TITLE
types: qorus oload: RUNTIME-TYPE-ERROR: <lvalue> expects type '*list', but got type 'integer' instead

### ISSUE THREAD

**Issue by pvanek** [qorelanguage/qore#2124] opened 2017-09-05 08:13 UTC
pvanek@spongebob:~/src/qorus/qorus/test> oload -lR qorus-tests.qrf
ends in runtime type error

Minimal example:

```
%new-style

# Taken from Qorus 3.1.1 branch
# System exception: /srv/qorus-dev/bin/oload:4430: RUNTIME-TYPE-ERROR: <lvalue> expects type '*list', but got type 'integer' instead
# call stack:
#  oload::updateValidationLists() called at /srv/qorus-dev/bin/oload:513 (user function)


        hash valfh;              # hash of function_instanceids to be used for validation in case of option "-l"

        # hash of function_instanceids inserted that possibly add new versions to existing library functions to be used for validation in case of option "-l"
        hash valflh = ( 1 : True);

        # list of function IDs
        *softlist fl = map $1.toInt(), keys valfh;
        # list of potential library function IDs
        *list fll = fl;
        map fll += $1.toInt(), keys valflh;
```

```
unhandled QORE System exception thrown in TID 1 at 2017-09-05 09:55:28.171645 Tue +02:00 (CEST) at /export/home/pvanek/t.q:18
RUNTIME-TYPE-ERROR: <lvalue> expects type '*list', but got type 'integer' instead
```

**Comment by davidnich** [comment] 2017-09-05 15:43
this bug also is reproducible with Qore 0.8.11.1 and 0.8.12.10, so it's not a regression introduced in 0.8.13; note that the issue is reproducible in a simpler form:
```
qore -nX '*list l += 1'
```

The issue is that `*list` types when assigned `NOTHING` do not get promoted to a list with the `+=` operator like the `list` type or `softlist` type does - so you could say that this is a design bug, but since it's been there so long, changing it might break things as well - I would prefer to fix this in the Qorus source you quoted, so I'll open an issue there.

**Comment by davidnich** [comment] 2017-09-05 16:04
closing with `wontfix` because it could break things - the bug in the source program is being fixed though (merge request already pending)

**Closed as completed by davidnich** 2017-09-05 16:04 UTC
Labels: bug, wontfix, invisible, types
