### ISSUE TITLE
Segfault when redeclaring global hash variable

### ISSUE THREAD

**Issue by omusil24** [qorelanguage/qore#891] opened 2016-05-23 10:42 UTC
```
#!/usr/bin/env qore
# -*- mode: qore; indent-tabs-mode: nil -*-

%new-style
%enable-all-warnings
%require-types
%strict-args

# has to have exactly 4 keys/values, otherwise PARSE-EXCEPTION is thrown: 
#     "global variable '::h' has already been declared in this Program object"
our hash h = (
    "1" : "",
    "2" : "",
    "3" : "",
    "4" : "",
);

%exec-class A

public class A {
    constructor() {
        # any of these work
        our hash h = {};
        #our int h = 5;
        #our list h = ();
        #our float h = 2;
    }
}
```

@tethal

**Comment by tethal** [comment] 2016-05-23 11:10
~~Seems related to #233~~

This crashes as well:

```
%new-style
%enable-all-warnings
%require-types
%strict-args

our hash h = (
    "1" : "",
    "2" : "",
    "3" : "",
    "4" : "",
);

our float h = 2;
```

Does not crash if the hash contains 5-8 members, if there are more than 8, then it crashes at different places in the code

**Comment by tethal** [comment] 2016-05-23 14:15
When resolving global variables in parseResolveGlobalVars(), duplicate global variables (instances of the Var class) are deallocated when the parse error is reported. The problem is that after that the code is still being parsed - VarRefNode's parseInitImpl() accesses the deallocated Var instance, which may or may not have already been overwritten by another object (that's why the crash does not occur if the initial hash size is not 4).
The fix is to skip further parsing if an error is reported by parseResolveGlobalVars().

**Closed as completed** 2016-05-23 14:30 UTC
Labels: bug, fixed
