### ISSUE TITLE
SIGSEGV when there is a function/const hash cross referenced

### ISSUE THREAD

**Issue by pvanek** [qorelanguage/qore#3027] opened 2018-10-04 14:28 UTC
I don't say it's correct programming technique, but it should not "Segmentation fault (core dumped)" at all...

example:
```
%new-style

sub foo() {
    hash h = T{"foo"}; # T is a constant which calls this function
    return h.a;
}

const T = {
    "foo": { "a": 1, "b": foo()}, # this function foo() uses constant T to access its data
};
```

**Comment by davidnich** [comment] 2018-10-27 16:32
@pvanek I cannot reproduce with Qore 0.8.13.* or develop - I get:
```
qore -ne '%new-style
> 
> sub foo() {
>     hash h = T{"foo"}; # T is a constant which calls this function
>     return h.a;
> }
> 
> const T = {
>     "foo": { "a": 1, "b": foo()}, # this function foo() uses constant T to access its data
> };'
unhandled QORE System exception thrown in TID 1 at 2018-10-27 17:14:40.592686 Sat +02:00 (CEST) at <command-line>:8-10
PARSE-EXCEPTION: recursive constant reference found to constant 'T'
```

**Comment by davidnich** [comment] 2018-10-27 16:42
@pvanek here is a pull request from a branch with the test - it's passing jenkins as well:
https://github.com/qorelanguage/qore/pull/3068

here is a link to the test; please check it: https://github.com/qorelanguage/qore/pull/3068/files

**Comment by davidnich** [comment] 2018-10-27 20:39
@pvanek can we close this issue?

**Comment by omusil24** [comment] 2018-10-29 05:02
Not fixed actually. Try this:

```
%new-style

sub foo() {
    hash h = T{"foo"}; # T is a constant which calls this function
    return h.b;
}

const T = {
    "foo": { "a": 1, "b": foo()}, # this function foo() uses constant T to access its data
};

foo();
```

Segfaults in 0.8.13.8:
```
$ qore -V
QORE for Linux x86_64 (64-bit build), Copyright (C) 2003 - 2018 David Nichols
version 0.8.13.8 (builtin features: sql, threads, DGC)
  git hash: 0751cc19a68f9489e20dc017b58bd3b5fae1b974
  module API: 0.21 (0.20, 0.19, 0.18, 0.17, 0.16, 0.15, 0.14, 0.13, 0.12, 0.11, 0.10, 0.9, 0.8, 0.7, 0.6, 0.5)
  build host: Linux x86_64 x86_64 GNU/Linux
  C++ compiler: g++
  CFLAGS: -DNDEBUG=1 -DHAVE_UNIX_CONFIG_H -D_QORE_LIB_INTERN -DMODULE_DIR="/usr/lib/x86_64-linux-gnu/qore-modules" -DMODULE_VER_DIR="/usr/lib/x86_64-linux-gnu/qore-modules/0.8.13" -DUSER_MODULE_DIR="/usr/share/qore-modules" -DUSER_MODULE_VER_DIR="/usr/share/qore-modules/0.8.13" -g -O2 -m64 -fno-strict-aliasing -D_THREAD_SAFE -pthread -Wall -lm
  LDFLAGS: -L/usr/lib/x86_64-linux-gnu -lmpfr -L/usr/lib/x86_64-linux-gnu -lz -L/usr/lib/x86_64-linux-gnu -lpcre -L/usr/lib/x86_64-linux-gnu -lbz2 -L/usr/lib/x86_64-linux-gnu -lssl -lcrypto -pthread -lm
  MPFR: runtime: 4.0.1 built with: 4.0.1 (4.0.1)
```

**Comment by davidnich** [comment] 2018-10-29 06:12
@omusil24 ok thank you

**Closed as completed** 2018-10-29 15:17 UTC
Labels: bug, fixed, c++
