### ISSUE TITLE
Memory leak in reference.qtest

### ISSUE THREAD

**Issue by omusil24** [qorelanguage/qore#1638] opened 2017-02-03 09:16 UTC
examples/test/qore/vars/reference.qtest

valgrind output: https://gist.github.com/omusil24/09c596d5532d69383466b6ac1f4d784e

**Comment by davidnich** [comment] 2017-02-05 08:09
in fact the root cause of this was an incorrect fix in #1617 - this should be detected at assignment time (which is what causes the memory leak) and not when the reference is used

**Comment by davidnich** [comment] 2017-02-05 08:13
this will be fixed in #1617

**Closed as completed by davidnich** 2017-02-05 08:13 UTC
Labels: bug, duplicate, memory leak, fixed, c++
